version: '3.7'

services:
    db:
        image: postgres
        
       
        environment: 
            - POSTGRES_DB=capstone
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=t..w..o..
    web:
        build: .
        command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
                - .:/code
        ports:
                - "8000:8000"
        depends_on: 
                - db
                
